# Enable C++ support
sudo: false
language: cpp
# Compiler selection
compiler:
  - clang
  - gcc
# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && make

after_success:
  - bash <(curl -s https://codecov.io/bash)

install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - clang
