# Enable C++ support
language: cpp
# Compiler selection
compiler:
  - clang
  - gcc
# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && make

after_success:
  - bash <(curl -s https://codecov.io/bash)

addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
      packages:
      - clang-3.7
      - g++-5
      - gcc-5
